name: Test
on:
  push:
    paths:
      - '**.ts'
      - '**.js'
      - 'scripts/*.sh'
      - 'yarn.lock'
      - 'tsconfig.json'
      - 'package.json'
  pull_request:
    paths:
      - '**.ts'
      - '**.js'
      - 'scripts/*.sh'
      - 'yarn.lock'
      - 'tsconfig.json'
      - 'package.json'
  workflow_dispatch:

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.ref }}
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.13'
    - name: Install dependencies
      run: |
        npm cache clean
        npm install --update-checksums
        npm install
    - name: Run tests
      run: |
        npm run retest
